name: Add Baidu Site Verification Meta Tag

on:
  push:
    branches:
      - main  # Adjust this branch name as needed

jobs:
  add-meta-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Add Meta Tag
        run: |
          sed -i 's/<head>/<head>\n<meta name="baidu-site-verification" content="codeva-RatOJrEmaq" \/>/' index.html
          git config --global user.email "linlinlin1992@sina.com"
          git config --global user.name "linlinlin1992"
          git add index.html
          git commit -m "Add Baidu Site Verification Meta Tag"
          git push
